# 常用粤语词汇校正（客服场景）
CANTONESE_CORRECTIONS = {
    "是不是": "係唔係",
    "这样": "咁樣",
    "那个": "嗰個",
    "这里": "呢度",
    "什么时候": "幾時",
    "为什么": "點解",
    "很好": "好好",
    "没有": "冇",
    "的": "嘅",
    "他": "佢",
    "我们": "我哋",
    "可以": "得",
    "请问": "請問",
    "需要": "要",
    "现在": "而家",
    "问题": "問題",
    "谢谢": "多謝",
    "对不起": "唔好意思",
    "订单": "訂單",
    "服务": "服務",
    "帮助": "幫忙",
    "明白": "明白",
    "确认": "確認",
    "稍等": "等一等"
}

# 常用英文词汇校正（客服场景）
ENGLISH_CORRECTIONS = {
    "there": "their",
    "your": "you're",
    "its": "it's",
    "to": "too",
    "then": "than",
    "weather": "whether",
    "accept": "except",
    "OK": "okay",
    "Punky": "Funky",
    "Punky Finance": "Funky Finance",
    "order": "order",
    "service": "service",
    "please": "please",
    "thank you": "thank you",
    "sorry": "sorry",
    "confirm": "confirm",
    "wait": "wait",
    "help": "help",
    "issue": "issue",
    "problem": "problem",
    "now": "now",
    "understand": "understand",
    "Punky Finance": "Funky Finance"
}